//搜索栏的状态
export const CHANGE_SIDEBAR = 'CHANGE_SIDEBAR'
//搜索栏的状态
export const CHANGE_SEARCH_STATUS = 'CHANGE_SEARCH_STATUS'
//登录状态
export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS'
//登录界面状态
export const CHANGE_LOGINVIEW_STATUS = 'CHANGE_LOGINVIEW_STATUS'
//切换动画状态
export const CHANGE_LOGINTRANSTION = 'CHANGE_LOGINTRANSTION'
export const CHANGE_MAINTRANSTION = 'CHANGE_MAINTRANSTION'

//关注的歌手
export const SET_FOCUS_SINGER = 'SET_FOCUS_SINGER'
export const CONCAT_FOCUS_SINGER = 'CONCAT_FOCUS_SINGER'
//取消关注
export const SET_CANCEL_FOCUS = 'SET_CANCEL_FOCUS'

//**********************play

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'
export const SET_PLAY_STATE = 'SET_PLAY_STATE'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
export const SET_PLAY_LIST = 'SET_PLAY_LIST'
export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'
export const SET_PLAY_MODE = 'SET_PLAY_MODE'