export const CHANGE_SEARCH_STATUS='CHANGE_SEARCH_STATUS'
export const CHANGE_LOGIN_STATUS='CHANGE_LOGIN_STATUS'

export const CHANGE_LOGINVIEW_STATUS='CHANGE_LOGINVIEW_STATUS'
export const CHANGE_LOGINTRANSTION='CHANGE_LOGINTRANSTION'